
paths:
  local:
    input_path: /home/jenseirik/OneDrive/ETH/master/3d-vision/project/data
    output_path: /home/jenseirik/OneDrive/ETH/master/3d-vision/project/out
  euler:
    input_path: /cluster/project/infk/courses/252-0579-00L/group10/ego-speed-estimation/data
    output_path: /cluster/project/infk/courses/252-0579-00L/group10/ego-speed-estimation/out

seed: 12345678

dataloader:
  dataset_name: 'comma-ai'
  dataloader_name: 'default'

preprocessing:


model:
  model_name: 'cnn-lstm'
  num_epochs: 1
  batch_size: 8
  learning_rate: 0.001
