
paths:
  local:
    input_path: /home/christopher/ETH/MSc_4/3DVision/code/ego-speed-estimation/data
    output_path: /home/christopher/ETH/MSc_4/3DVision/code/ego-speed-estimation/out
  euler:
    input_path: /cluster/project/infk/courses/252-0579-00L/group10/ego-speed-estimation/data
    output_path: /cluster/project/infk/courses/252-0579-00L/group10/ego-speed-estimation/out

seed: 12345678

dataloader:
  dataset_name: 'comma-ai'
  dataloader_name: 'default'

preprocessing:
  data_transform: 'null'
  video_transform: 'depth_opticalflow'

model:
  model_name: 'depth_opticalflow'
  num_epochs: 10
  batch_size: 8
  learning_rate: 0.001