dirs:
  root: 'comma2k19'
  train: ['Chunk_1', 'Chunk_2', 'Chunk_3', 'Chunk_4', 'Chunk_5', 'Chunk_6']
  val: ['Chunk_7', 'Chunk_8']
  test: ['Chunk_9', 'Chunk_10']

video_length: 1200
sample_length: 60

mapping:
  train: "comma2k19/mapping_train.pkl"
  val: "comma2k19/mapping_val.pkl"
  test: "comma2k19/mapping_test.pkl"