# Defines data splits
dirs:
  # Path between paths.input_path from default.yaml and the following list of directories
  root: 'comma2k19'
  # Directories with data used for training
  train: ['Chunk_1', 'Chunk_2', 'Chunk_3', 'Chunk_4', 'Chunk_5', 'Chunk_6']
  # Directories with data used for validation
  val: ['Chunk_7', 'Chunk_8']
  # Directories with data used for testing
  test: ['Chunk_9', 'Chunk_10']

# Number of frames in video as defined in data set (Should not be modified)
video_length: 1200
# Number of consecutive frames that are sampled during training/testing
sample_length: 60

# Set this to true if only videos recorded during the day should be included in the test data
day_only: false

# Define names of files that store mappings of paths to data used during data loading.
mapping:
  train: "comma2k19/mapping_train.pkl"
  val: "comma2k19/mapping_val.pkl"
  test: "comma2k19/mapping_test.pkl"
  test_day: "comma2k19/mapping_test_day.pkl"
  # Defines if mappings should be rebuild during initialization of data loader
  # This must be true if data directory is modified, afterwards it can be set to false
  rebuild_mapping: true