dirs:
  root: 'comma2k19'
  train: ['Chunk_1', 'Chunk_2', 'Chunk_3', 'Chunk_4', 'Chunk_5', 'Chunk_6']
  val: ['Chunk_7', 'Chunk_8']
  test: ['Chunk_9', 'Chunk_10']

video_length: 1200
sample_length: 40

mapping:
  train: "/cluster/project/infk/courses/252-0579-00L/group10/ego-speed-estimation/data/comma2k19/mapping_train.pkl"
  val: "/cluster/project/infk/courses/252-0579-00L/group10/ego-speed-estimation/data/comma2k19/mapping_val.pkl"
  test: "/cluster/project/infk/courses/252-0579-00L/group10/ego-speed-estimation/data/comma2k19/mapping_test.pkl"
